=== enbility/devices/schema/device.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "EEBUS device summary schema",
  "$ref": "#/definitions/root",
  "definitions": {
    "root": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "product": {
          "type": "string",
          "description": "Product or service name"
        },
        "updated": {
          "type": "string",
          "description": "The date DD.MM.YYYY the provided data was gathered"
        },
        "files": {
          "type": "object",
          "additionalProperties": false,
          "description": "Filenames for the source EEBUS SPINE data",
          "properties": {
            "discovery": {
              "type": "string",
              "description": "The filename of the NodeManagementDetailedDiscoveryData response content"
            },
            "usecase": {
              "type": "string",
              "description": "The filename of the NodeManagementUseCaseData response content"
            }
          }
        },
        "versions": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "firmware": {
              "type": "string",
              "description": "The version of the devices firmware or service that was used to gather the data"
            },
            "ship": {
              "type": "string",
              "description": "The SHIP version that is supported"
            },
            "spine": {
              "type": "string",
              "description": "The SPINE version that is supported"
            }
          }
        },
        "devicetype": {
          "type": "string",
          "description": "The 'devicetype' that is being reported in 'NodeManagementDetailedDiscoveryData'"
        },
        "iscem": {
          "type": "boolean",
          "description": "Set to 'true' if the device is a energy management system"
        },
        "usecases": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "name": {
                "type": "string",
                "description": "The usecase 'name' value of the supported use case defined in 'usecases.json'"
              },
              "version": {
                "type": "string",
                "description": "The version of the use case reported as being supported"
              },
              "invalid": {
                "type": "boolean",
                "description": "Set to 'false' if the use case is reported as being supported but is not implemented"
              },
              "scenarios": {
                "type": "array",
                "description": "A list of the supported scenarios",
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "id": {
                      "type": "integer",
                      "description": "The scenario ID as defined in the use case"
                    },
                    "invalid": {
                      "type": "boolean",
                      "description": "Set to 'false' if the scenario is reported as being supported but is not implemented"
                    }
                  },
                  "required": ["id"]
                }
              },
              "actor": {
                "$ref": "#/definitions/actor",
                "description": "The actor reported by the device for this use case"
              },
              "correctedactor": {
                "$ref": "#/definitions/actor",
                "description": "If the reported actor is invalid, this contains the actor it should have instead"
              },
              "entityid": {
                "type": "array",
                "description": "The SPINE entity ID array this use case & actor is implemented in",
                "items": {
                  "type": "integer",
                  "description": "The SPINE entity ID"
                }
              },
              "notes": {
                "type": "string",
                "description": "Additional notes, findings about the use case and its scenarios"
              }
            },
            "required": ["name", "version", "scenarios"]
          }
        },
        "features": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "entityid": {
                "type": "array",
                "description": "The SPINE entity ID array these features are implemented in",
                "items": {
                  "type": "integer",
                  "description": "The SPINE entity ID"
                }
              },
              "entitytype": {
                "type": "string",                    
                "description": "The SPINE entity type this feature is supported by",
                "enum": ["CEM", "EVSE", "EV", 
                  "ElectricityStorageSystem", 
                  "GridConnectionPointOfPremises", "BatterySystem",
                  "ElectricityGenerationSystem", "PVSystem",
                  "HeatPumpAppliance", "Generic"]
              },
              "role": {
                "type": "string",
                "description": "The feature role",
                "enum": ["server", "client"]
              },
              "features": {
                "type": "array",
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "type": {
                      "type": "string",
                      "description": "The SPINE feature type"
                    },
                    "invalid": {
                      "type": "boolean",
                      "description": "Set to 'false' if the feature is reported as being supported but is not implemented"
                    }
                  }
                }
              },
              "notes": {
                "type": "string",
                "description": "Additional notes, findings about the entities features"
              }
            }
          }
        },
        "notes": {
          "type": "string",
          "description": "Additional notes, findings about the device"
        }
      },
      "required": ["product", "updated", "files", "versions"]
    },
    "actor": {
      "type": "string",
      "enum": [
        "Battery",
        "BatterySystem",
        "CEM",
        "ConfigurationAppliance",
        "Compressor",
        "ControllableSystem",
        "DHWCircuit",
        "EnergyGuard",
        "EnergyBroker",
        "EnergyConsumer",
        "EVSE",
        "EV",
        "GridConnectionPoint",
        "HeatPump",
        "HeatingCircuit",
        "HeatingZone",
        "HVACRoom",
        "Inverter",
        "MonitoredUnit",
        "MonitoringAppliance",
        "OutdoorTemperatureSensor",
        "PVString",
        "PVSystem",
        "VisualizationAppliance"
      ]
    }
  }
}

=== enbility/devices/spelsberg/wallbox-smart-pro/device.json
{
  "product": "Spelsberg Wallbox Smart Pro",
  "updated": "15.05.2023",
  "files": {
    "discovery": "discovery-data.json",
    "usecase": "usecase-data.json"
  },
  "versions": {
    "firmware": "5.30.0-15956",
    "ship": "1.0",
    "spine": "1.3.0"
  },
  "devicetype": "Generic",
  "usecases": [
    {
      "name": "overloadProtectionByEvChargingCurrentCurtailment",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "EV"
    },
    {
      "name": "evCommissioningAndConfiguration",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2,
          "invalid": true
        },
        {
          "id": 3,
          "invalid": true
        },
        {
          "id": 4,
          "invalid": true
        },
        {
          "id": 5,
          "invalid": true
        },
        {
          "id": 6,
          "invalid": true
        },
        {
          "id": 7
        },
        {
          "id": 8
        }
      ],
      "actor": "EV",
      "notes": "ISO15118 scenarios (3-6) are reported as being supported, even though there is no ISO15118 EV connected and the ISO15118 support turned off."
    },
    {
      "name": "measurementOfElectricityDuringEvCharging",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "EV"
    },
    {
      "name": "optimizationOfSelfConsumptionDuringEvCharging",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1,
          "invalid": true
        },
        {
          "id": 2,
          "invalid": true
        },
        {
          "id": 3,
          "invalid": true
        }
      ],
      "actor": "EV",
      "invalid": true,
      "notes": "ISO15118 scenarios (1, 2, 3) are reported as being supported, even though there is no ISO15118 EV connected and the ISO15118 support turned off."
    },
    {
      "name": "coordinatedEvCharging",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1,
          "invalid": true
        },
        {
          "id": 2,
          "invalid": true
        },
        {
          "id": 3,
          "invalid": true
        },
        {
          "id": 4,
          "invalid": true
        },
        {
          "id": 5,
          "invalid": true
        },
        {
          "id": 6,
          "invalid": true
        },
        {
          "id": 7,
          "invalid": true
        },
        {
          "id": 8,
          "invalid": true
        }
      ],
      "actor": "EV",
      "invalid": true,
      "notes": "ISO15118 scenarios (1-8) are reported as being supported, even though there is no ISO15118 EV connected and the ISO15118 support turned off."
    },
    {
      "name": "evseCommissioningAndConfiguration",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        }
      ],
      "actor": "EVSE"
    },
    {
      "name": "evChargingSummary",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        }
      ],
      "actor": "EVSE",
      "invalid": true,
      "notes": "ISO15118 scenario (1) is reported as being supported, even though there is no ISO15118 EV connected and the ISO15118 support turned off."
    }
  ],
  "features": [
    {
      "entitytype": "EVSE",
      "entityid": [
        1
      ],
      "role": "server",
      "features": [
        {
          "type": "DeviceClassification"
        },
        {
          "type": "Bill"
        },
        {
          "type": "DeviceDiagnosis"
        }
      ]
    },
    {
      "entitytype": "EV",
      "entityid": [
        1,
        1
      ],
      "role": "server",
      "features": [
        {
          "type": "DeviceClassification"
        },
        {
          "type": "DeviceDiagnosis"
        },
        {
          "type": "ElectricalConnection"
        },
        {
          "type": "LoadControl"
        },
        {
          "type": "Measurement"
        },
        {
          "type": "DeviceConfiguration"
        },
        {
          "type": "TimeSeries",
          "invalid": true
        },
        {
          "type": "IncentiveTable",
          "invalid": true
        },
        {
          "type": "Identification",
          "invalid": true
        }
      ],
      "notes": "The features \"TimeSeries\", \"IncentiveTable\", and \"Identification\" require the EV to communicate via ISO15118, which is disabled in the device setup and no compatible EV was connected anyway."
    },
    {
      "entitytype": "EV",
      "entityid": [
        1,
        1
      ],
      "role": "client",
      "features": [
        {
          "type": "Generic"
        }
      ]
    }
  ]
}

=== enbility/devices/porsche/mobile-charger-connect/device.json
{
  "product": "Porsche Mobile Charger Connect",
  "updated": "12.04.2023",
  "files": {
    "discovery": "discovery-data.json",
    "usecase": "usecase-data.json"
  },
  "versions": {
    "firmware": "3014",
    "ship": "1.0",
    "spine": "1.1.1"
  },
  "devicetype": "ChargingStation",
  "usecases": [
    {
      "name": "evseCommissioningAndConfiguration",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        }
      ],
      "actor": "EV",
      "correctedactor": "EVSE",
      "notes": "The actor should be \"EVSE\"."
    },
    {
      "name": "evCommissioningAndConfiguration",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        },
        {
          "id": 4
        },
        {
          "id": 5
        },
        {
          "id": 6
        },
        {
          "id": 7
        },
        {
          "id": 8
        }
      ],
      "actor": "EV"
    },
    {
      "name": "measurementOfElectricityDuringEvCharging",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "EV"
    },
    {
      "name": "overloadProtectionByEvChargingCurrentCurtailment",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "EV"
    },
    {
      "name": "optimizationOfSelfConsumptionDuringEvCharging",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "EV"
    },
    {
      "name": "coordinatedEvCharging",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        },
        {
          "id": 4
        },
        {
          "id": 5
        },
        {
          "id": 6
        },
        {
          "id": 7
        },
        {
          "id": 8
        }
      ],
      "actor": "EV"
    },
    {
      "name": "evStateOfCharge",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        }
      ],
      "actor": "EV"
    },
    {
      "name": "evChargingSummary",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        }
      ],
      "actor": "EV"
    }
  ],
  "features": [
    {
      "entitytype": "EVSE",
      "entityid": [
        1
      ],
      "role": "server",
      "features": [
        {
          "type": "DeviceClassification"
        },
        {
          "type": "DeviceDiagnosis"
        },
        {
          "type": "Bill"
        }
      ]
    },
    {
      "entitytype": "EVSE",
      "entityid": [
        1
      ],
      "role": "client",
      "features": [
        {
          "type": "DeviceDiagnosis"
        },
        {
          "type": "DeviceClassification"
        }
      ]
    },
    {
      "entitytype": "EV",
      "entityid": [
        1,
        1
      ],
      "role": "server",
      "features": [
        {
          "type": "LoadControl"
        },
        {
          "type": "ElectricalConnection"
        },
        {
          "type": "Measurement"
        },
        {
          "type": "DeviceConfiguration"
        },
        {
          "type": "DeviceClassification"
        },
        {
          "type": "TimeSeries"
        },
        {
          "type": "IncentiveType"
        },
        {
          "type": "DeviceDiagnosis"
        },
        {
          "type": "Identification"
        }
      ]
    }
  ]
}

=== enbility/devices/evcc.io/evcc/device.json
{
  "product": "evcc.io",
  "updated": "12.04.2023",
  "files": {
    "discovery": "discovery-data.json",
    "usecase": "usecase-data.json"
  },
  "versions": {
    "firmware": "0.115.0",
    "ship": "1.0",
    "spine": "1.1.1"
  },
  "devicetype": "EnergyManagementSystem",
  "iscem": true,
  "usecases": [
    {
      "name": "evseCommissioningAndConfiguration",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        }
      ],
      "actor": "CEM"
    },
    {
      "name": "evCommissioningAndConfiguration",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        },
        {
          "id": 4
        },
        {
          "id": 5
        },
        {
          "id": 6
        },
        {
          "id": 7
        },
        {
          "id": 8
        }
      ],
      "actor": "CEM"
    },
    {
      "name": "measurementOfElectricityDuringEvCharging",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "CEM"
    },
    {
      "name": "overloadProtectionByEvChargingCurrentCurtailment",
      "version": "1.0.1b",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "CEM"
    },
    {
      "name": "evStateOfCharge",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        },
        {
          "id": 4
        }
      ],
      "actor": "CEM",
      "notes": "The actor is wrong and should be \"MonitoringAppliance\""
    },
    {
      "name": "optimizationOfSelfConsumptionDuringEvCharging",
      "version": "1.0.1b",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "CEM"
    }
  ],
  "features": [
    {
      "entitytype": "CEM",
      "entityid": [
        1
      ],
      "role": "server",
      "features": [
        {
          "type": "DeviceClassification"
        },
        {
          "type": "DeviceDiagnosis"
        }
      ]
    },
    {
      "entitytype": "CEM",
      "entityid": [
        1
      ],
      "role": "client",
      "features": [
        {
          "type": "DeviceClassification"
        },
        {
          "type": "DeviceDiagnosis"
        },
        {
          "type": "DeviceConfiguration"
        },
        {
          "type": "ElectricalConnection"
        },
        {
          "type": "Measurement"
        },
        {
          "type": "LoadControl"
        },
        {
          "type": "Identification"
        }
      ]
    }
  ]
}

=== enbility/devices/vaillant/vr920/device.json
{
  "product": "Vaillant VR920",
  "updated": "19.02.2024",
  "files": {
    "discovery": "discovery-data.json",
    "usecase": "usecase-data.json"
  },
  "versions": {
    "firmware": "Unknown",
    "ship": "1.0",
    "spine": "1.1.1"
  },
  "devicetype": "Generic",
  "features": [
    {
      "entitytype": "Generic",
      "role": "client",
      "features": [
        {
          "type": "Generic"
        }
      ]
    }
  ],
  "notes": "This device only supports EEBUS use cases that are not open source and does not announce any of them."
}

=== enbility/devices/elli/charger-connect-pro/device.json
{
  "product": "Elli Connect / Pro",
  "updated": "12.04.2023",
  "files": {
    "discovery": "discovery-data.json",
    "usecase": "usecase-data.json"
  },
  "versions": {
    "firmware": "v3.8.12",
    "ship": "1.0",
    "spine": "1.3.0"
  },
  "devicetype": "Generic",
  "usecases": [
    {
      "name": "evseCommissioningAndConfiguration",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        }
      ],
      "actor": "EVSE"
    },
    {
      "name": "evCommissioningAndConfiguration",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3,
          "invalid": true
        },
        {
          "id": 4,
          "invalid": true
        },
        {
          "id": 5,
          "invalid": true
        },
        {
          "id": 6,
          "invalid": true
        },
        {
          "id": 7,
          "invalid": true
        },
        {
          "id": 8
        }
      ],
      "actor": "EV",
      "notes": "Only the scenarios \"EV connected\", \"EV sends communication standard\" and \"EV disconnected\" are really supported. All other scenarios require the EV to communicate via ISO15118 with the EVSE, which this device is not capable of."
    },
    {
      "name": "measurementOfElectricityDuringEvCharging",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2,
          "invalid": true
        },
        {
          "id": 3,
          "invalid": true
        }
      ],
      "actor": "EV",
      "notes": "The Elli Charger Connect does not contain a meter. For that model the provided measurements are only assumptions. Also only the scenario \"Measure EV charging current\" is really supported."
    },
    {
      "name": "overloadProtectionByEvChargingCurrentCurtailment",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "EV"
    },
    {
      "name": "optimizationOfSelfConsumptionDuringEvCharging",
      "version": "1.0.1",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        }
      ],
      "actor": "EV",
      "notes": "Self consumption information from the HEMS is transformed into overload protection values."
    },
    {
      "name": "coordinatedEvCharging",
      "version": "1.0.1",
      "invalid": true,
      "scenarios": [
        {
          "id": 1,
          "invalid": true
        },
        {
          "id": 2,
          "invalid": true
        },
        {
          "id": 3,
          "invalid": true
        },
        {
          "id": 4,
          "invalid": true
        },
        {
          "id": 5,
          "invalid": true
        },
        {
          "id": 6,
          "invalid": true
        },
        {
          "id": 7,
          "invalid": true
        },
        {
          "id": 8,
          "invalid": true
        }
      ],
      "actor": "EV",
      "notes": "This use case is reported as being available, but it is not. The use case requires the EV to communicate via ISO15118, which this device is not capable of."
    },
    {
      "name": "evChargingSummary",
      "version": "1.0.1",
      "invalid": true,
      "scenarios": [
        {
          "id": 1,
          "invalid": true
        }
      ],
      "actor": "EV",
      "notes": "This is use case is reported as being available, but not implemented."
    }
  ],
  "features": [
    {
      "entitytype": "EVSE",
      "entityid": [
        1
      ],
      "role": "server",
      "features": [
        {
          "type": "DeviceClassification"
        },
        {
          "type": "Bill",
          "invalid": true
        },
        {
          "type": "DeviceDiagnosis"
        }
      ],
      "notes": "This \"Bill\" feature is not implemented."
    },
    {
      "entitytype": "EV",
      "entityid": [
        1,
        1
      ],
      "role": "server",
      "features": [
        {
          "type": "DeviceClassification"
        },
        {
          "type": "DeviceDiagnosis"
        },
        {
          "type": "ElectricalConnection"
        },
        {
          "type": "LoadControl"
        },
        {
          "type": "Measurement"
        },
        {
          "type": "DeviceConfiguration"
        },
        {
          "type": "TimeSeries",
          "invalid": true
        },
        {
          "type": "IncentiveTable",
          "invalid": true
        },
        {
          "type": "Identification",
          "invalid": true
        }
      ],
      "notes": "The features \"TimeSeries\", \"IncentiveTable\", and \"Identification\" require the EV to communicate via ISO15118, which this device is not capable of. These features are not implemented."
    },
    {
      "entitytype": "EV",
      "entityid": [
        1,
        1
      ],
      "role": "client",
      "features": [
        {
          "type": "Generic"
        }
      ]
    }
  ]
}

=== enbility/devices/viessmann/vitoconnect/device.json
{
  "product": "Viessmann Vitoconnect",
  "updated": "13.10.2022",
  "files": {
    "discovery": "discovery-data.json",
    "usecase": "usecase-data.json"
  },
  "versions": {
    "firmware": "Unknown",
    "ship": "1.0",
    "spine": "1.2.0"
  },
  "devicetype": "Generic",
  "usecases": [
    {
      "name": "monitoringAndControlOfSmartGridReadyConditions",
      "version": "1.0.0",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        }
      ],
      "actor": "HeatPump"
    },
    {
      "name": "monitoringOfPowerConsumption",
      "version": "1.0.0 draft3",
      "scenarios": [
        {
          "id": 1
        },
        {
          "id": 2
        },
        {
          "id": 3
        },
        {
          "id": 4
        }
      ],
      "actor": "HeatPump"
    }
  ],
  "features": [
    {
      "entitytype": "HeatPumpAppliance",
      "entityid": [
        1
      ],
      "role": "server",
      "features": [
        {
          "type": "DeviceClassification"
        },
        {
          "type": "ElectricalConnection"
        },
        {
          "type": "HVAC"
        },
        {
          "type": "Measurement"
        }
      ]
    }
  ]
}
